#
# Steve's shortcuts
#

all:

uml:

	plantuml -tpng dx_database_schema.puml -o images

collect:

	nohup ./dx-cluster-file.py &

# Fix this to grab all files 

pull-data:

	wget http://jxqz.org/~steve/dx-data/dx_spots.1.txt
	wget http://jxqz.org/~steve/dx-data/dx_spots.2.txt
