{
 "title": "DX Ingest Monitoring",
 "description": "Scraper and Database Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Host Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Space",
   "type": "gauge",
   "description": "Percent Disk Used",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes / node_filesystem_size_bytes * 100)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "1min, 5min, 15min load",
   "gridPos": { "h": 9, "w": 13, "x": 7, "y": 1 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{__name__}}" },
    { "expr": "node_load5", "legendFormat": "{{__name__}}" },
    { "expr": "node_load15", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "Scraper Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Spot Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(dx_scraper_spots_stored_total[5m])) * 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Spots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dx_scraper_spots_total)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Database Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Latest Spots",
   "type": "table",
   "description": "Last 5 DX Spots",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "dx_analysis",
     "rawSql": "select timestamp, dx_call, frequency, spotter_call, comment from dx_spots order by id desc limit 5;"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Size in MB",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dataset": "dx_analysis",
     "rawSql": "SELECT pg_database_size('dx_analysis');"
    }
   ]
  }
 ]
}